columnSuffix: null
handle: lightswitchOn
instructions: null
name: 'Lightswitch ON'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
