columnSuffix: null
handle: seo
instructions: null
name: SEO
searchable: false
settings:
  createButtonLabel: SEO
  entryTypes:
    - 298deadf-cec5-45d8-8bf3-9434fe342718 # SEO
  includeTableView: false
  maxEntries: 1
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
