columnSuffix: null
handle: videoUrl
instructions: 'Enter a Vimeo or YouTube URL'
name: 'Video Url'
searchable: false
settings:
  maxLength: 255
  typeSettings:
    __assoc__:
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
